BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA rag;

CREATE TABLE rag.book (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    book_name TEXT NOT NULL,
    book_text TEXT NOT NULL
);

CREATE TABLE rag.book_passage (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES rag.book (id) ON DELETE CASCADE,
    passage_text TEXT NOT NULL,
    embedding VECTOR(1024)
);

COMMIT;
