// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package data

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/pgvector/pgvector-go"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const createBookPassages = `-- name: CreateBookPassages :batchexec
INSERT INTO rag.book_passage (book_id, passage_text, embedding)
VALUES (
    $1, $2, $3
)
`

type CreateBookPassagesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type CreateBookPassagesParams struct {
	BookID      int64
	PassageText string
	Embedding   pgvector.Vector
}

func (q *Queries) CreateBookPassages(ctx context.Context, arg []CreateBookPassagesParams) *CreateBookPassagesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BookID,
			a.PassageText,
			a.Embedding,
		}
		batch.Queue(createBookPassages, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &CreateBookPassagesBatchResults{br, len(arg), false}
}

func (b *CreateBookPassagesBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *CreateBookPassagesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
