// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/pgvector/pgvector-go"
)

type RagBook struct {
	ID       int64
	BookName string
	BookText string
}

type RagBookPassage struct {
	ID          int64
	BookID      int64
	PassageText string
	Embedding   pgvector.Vector
}
