// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"github.com/pgvector/pgvector-go"
)

type RagBook struct {
	ID   int64
	Name string
	Text string
}

type RagBookPassage struct {
	ID        int64
	BookID    int64
	Text      string
	Embedding pgvector.Vector
}
