// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package data

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const similaritySearch = `-- name: SimilaritySearch :many
SELECT
    id,
    text,
    CAST(1 - (embedding <=> $1) AS REAL) AS similarity
FROM rag.book_passage
WHERE book_id = $1
ORDER BY embedding <=> $2
LIMIT $3
`

type SimilaritySearchParams struct {
	Embedding   pgvector.Vector
	Embedding_2 pgvector.Vector
	Limit       int32
}

type SimilaritySearchRow struct {
	ID         int64
	Text       string
	Similarity float32
}

func (q *Queries) SimilaritySearch(ctx context.Context, arg SimilaritySearchParams) ([]SimilaritySearchRow, error) {
	rows, err := q.db.Query(ctx, similaritySearch, arg.Embedding, arg.Embedding_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SimilaritySearchRow
	for rows.Next() {
		var i SimilaritySearchRow
		if err := rows.Scan(&i.ID, &i.Text, &i.Similarity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
